### ISSUE TITLE
 INFUSION API ERROR

### ISSUE THREAD

**Issue by llagundimao** [nateleavitt/infusionsoft#12]
Hi everyone,
I'm new here on infusionsoft, I followed the instruction correctly, I provide correct configuration  
API URL & API Key.. but I'm having an error saying:

**\* INFUSION API ERROR: retrying 1 ***
**\* INFUSION API ERROR: retrying 2 ***
**\* INFUSION API ERROR: retrying 3 ***
**\* INFUSION API ERROR: retrying 4 ***
**\* INFUSION API ERROR: retrying 5 ***

And I view the the xml file It said, "<methodResponse>
<fault>
<value>
<struct>
<member>
<name>faultCode</name>
<value>
<i4>0</i4>
</value>
</member>
<member>
<name>faultString</name>
<value>
Failed to parse XML-RPC request: Premature end of file.
</value>
</member>
</struct>
</value>
</fault>
</methodResponse>"

Can anyone help me? Thanks in advance

**Comment by fastesol** [comment]
@llagundimao how where you able to fix this issue please?

**Comment by nateleavitt** [comment]
@fastesol  - it seemed like he fixed it after adding nokogiri to his gemfile.

**Comment by fastesol** [comment]
@nateleavitt Thank you for a quick response.

btw, I'm following the infusionsoft documentation [here](https://developer.infusionsoft.com/docs/xml-rpc/#contact-retrieve-a-contact)  and making request without using CURL (no API SDK) but having the same error.

`
		$url_token = 'http://api.infusionsoft.com/crm/xmlrpc/v1/?access_token='.$access_token;
		
		$curlPost = array(
						'access_token' => $access_token,
						'privateKey' => $api_key,
						'contactId' => 6171,
						'selectedFields' => array('email')
					);
		
		$ch = curl_init();
		curl_setopt($ch, CURLOPT_URL, $url_token);
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		curl_setopt($ch, CURLOPT_POST, 1);
		curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, FALSE);
		curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($curlPost));
		$res = curl_exec($ch);
		echo $res;`
