### ISSUE TITLE
missing key in documentation

### ISSUE THREAD

**Issue by proamateur** [nateleavitt/infusionsoft#27]
Sorry, but I couldn't find a way to edit the documentation so I'm submitting this as an issue. It's a quick fix.

http://rdoc.info/github/nateleavitt/infusionsoft/Infusionsoft/Client/Invoice:invoice_charge_invoice

the first key in invoice_charge_invoice is "Successful". In the documentation it's missing, it's:
"Returns:  (Hash) —
containing the following keys => [Boolean], 'Code' => [String], 'RefNum' => [String], 'Message' => [String]"

Cheers!

**Comment by nateleavitt** [comment]
Thanks!
