### ISSUE TITLE
InfusionSoft Using Oauth2

### ISSUE THREAD

**Issue by moorem** [nateleavitt/infusionsoft#35]
I'm new to infusionsoft and looking to use it in my application to save contacts. I'm not able to get app_url after registering an app on infusionsoft as i think they stop supporting old way and only way to use it through oauth2.
Can i use this gem to connect with the API now? Please help me how to use it with the api latest version.

**Comment by nateleavitt** [comment]
@moorem the app_url is your infusionsoft application url.

**Comment by nateleavitt** [comment]
I've started work on updating for the new Oath2 workflow.  Check for updates this week.
