### ISSUE TITLE
Nonename or servname not provided?

### ISSUE THREAD

**Issue by justuseapen** [nateleavitt/infusionsoft#36]
I put

gem 'infusionsoft'
in my gemfile.

I added my API Key and URL as environmental variables that get loaded into an initializer like so:

Infusionsoft.configure do |config|
  config.api_url = ENV['INFUSIONSOFT_URL'] # example infused.infusionsoft.com
  config.api_key = ENV['INFUSIONSOFT_API_KEY']
  config.api_logger = Logger.new("#{Rails.root}/log/infusionsoft_api.log") # optional logger file
end

But when I test the contact add service in my rails console I get this error:

SocketError: getaddrinfo: nodename nor servname provided, or not known
from /Users/Justus/.rbenv/versions/2.1.2/lib/ruby/2.1.0/net/http.rb:879:in `initialize'
Is anyone aware of a fix for this?

**Comment by nateleavitt** [comment]
@justuseapen have you been able to get this figured out?

**Comment by justuseapen** [comment]
Nope. I had to manually send Infusionsoft form data.
