### ISSUE TITLE
Infusionsoft::LoadingError: [Loading]Error loading follow-up sequence

### ISSUE THREAD

**Issue by rhnorment** [nateleavitt/infusionsoft#42]
I can add a new contact, but cannot seem to add a contact to a campaign.

Example:

```
contact_id = Infusionsoft.contact_add_with_dup_check({ FirstName:'Hank', LastName:'Hill', Email:'hank@gmail.com' }, 'EmailAndName')

Infusionsoft.contact_add_to_campaign(contact_id, 35)  //This throws the error.
```

Thoughts?

**Comment by nateleavitt** [comment]
Hey... what does the error look like? Do you see in your logs?

**Comment by rhnorment** [comment]
Nate - 

Stupid error on my part.  I had the API key configured incorrectly.  Everything is working perfectly.

Thanks for writing such an excellent and well-documented wrapper.

I’m an intermediate-level Rails developer looking for a code mentor.  Do you do any coaching for a fee?  I’d love to create what you did for another software service called Populi.

Kind Regards,  Hunt

**Comment by nateleavitt** [comment]
@rhnorment Let me know if you continue to see this issue.

**Comment by mhassaan** [comment]
Hi @nateleavitt  i am integrating this gem in my rails app and i am facing the same issue with some of the methods. Like when i try to make an api call to check for duplication 
`Infusionsoft.contact_add_with_dup_check({ FirstName:'Bill', LastName:'Joe', Email:'bill@gmail.com' }, 'ContactName')`
This throws an error 
`#<Infusionsoft::InvalidParameterError: [InvalidParameter]Not a valid Dup-check option: bill@gmail.com. Must user one of the following: Email, EmailAndName, EmailAndNameAndCompany>`

Any update on this ?
