### ISSUE TITLE
No Send

### ISSUE THREAD

**Issue by zephiro** [nateleavitt/infusionsoft#46]
Infusion Email Send no Work.

My code:

Infusionsoft.configure do |config|
        config.api_url = url
        config.api_key = api
        config.api_logger = Logger.new("#{Rails.root}/log/infusionsoft.log") 
      end

contact_list = [12, 6]
Infusionsoft.email_send(contact_list, "#{newsletter.from_email}", "email@domain.com", "", "", "Multipart", title, html, plain)

cat infusionsoft.log
INFO -- : CALL: APIEmailService.sendEmail api_url: xxx.infusionsoft.com api_key:xxxxx at:2015-09-28 13:38:09 -0500 args:[[12, 6], "email@domain.com", "email@domain.com", "", "", "Multipart", "this subject", "This HTML", "This Plain"]
INFO -- : RESULT: false

**Comment by nateleavitt** [comment]
@zephiro Is this still an issue for you?
