### ISSUE TITLE
funnel_achieve_goal returning weird error

### ISSUE THREAD

**Issue by sftsang** [nateleavitt/infusionsoft#48]
Hi there, I am making the following call to put a customer into a sequence:

`Infusionsoft.funnel_achieve_goal("no343","payingcustomer",1234)`

As far as I can tell this should work, but when I do that I get this error:

`RuntimeError: Wrong size. Was 1068, should be 307`

 Has this happened to anyone else before? How can I fix this?

Thanks!

**Comment by jamesmarrs** [comment]
Hello, I havent seen this particular error before, what version of of rails/ruby are you running? Do you have other integration's successfully running with this gem? Is there any more detail on the runtime error (log info, etc)?

**Comment by sftsang** [comment]
I am running rails 4.2.1 with ruby 2.1.1. 

I have successfully ran other queries with the gem with no errors, but I'm not sure if that's what you mean by other "integrations". 

The here is the full error message:

```ruby
RuntimeError: Wrong size. Was 1068, should be 308
	from /home/vagrant/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/xmlrpc/client.rb:511:in `do_rpc'
	from /home/vagrant/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/xmlrpc/client.rb:286:in `call2'
	from /home/vagrant/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/xmlrpc/client.rb:267:in `call'
	from /home/vagrant/.rvm/gems/ruby-2.1.1@ceratops/gems/infusionsoft-1.1.9/lib/infusionsoft/connection.rb:18:in `connection'
	from /home/vagrant/.rvm/gems/ruby-2.1.1@ceratops/gems/infusionsoft-1.1.9/lib/infusionsoft/request.rb:30:in `request'
	from /home/vagrant/.rvm/gems/ruby-2.1.1@ceratops/gems/infusionsoft-1.1.9/lib/infusionsoft/request.rb:6:in `get'
	from /home/vagrant/.rvm/gems/ruby-2.1.1@ceratops/gems/infusionsoft-1.1.9/lib/infusionsoft/client/funnel.rb:13:in `funnel_achieve_goal'
	from /home/vagrant/.rvm/gems/ruby-2.1.1@ceratops/gems/infusionsoft-1.1.9/lib/infusionsoft.rb:19:in `method_missing'
	from (irb):6
	from /home/vagrant/.rvm/gems/ruby-2.1.1@ceratops/gems/railties-4.2.1/lib/rails/commands/console.rb:110:in `start'
	from /home/vagrant/.rvm/gems/ruby-2.1.1@ceratops/gems/railties-4.2.1/lib/rails/commands/console.rb:9:in `start'
	from /home/vagrant/.rvm/gems/ruby-2.1.1@ceratops/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /home/vagrant/.rvm/gems/ruby-2.1.1@ceratops/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/vagrant/.rvm/gems/ruby-2.1.1@ceratops/gems/railties-4.2.1/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```
The infusionsoft_api.log doesn't say much more:

```ruby
I, [2015-10-28T16:45:56.642172 #2357]  INFO -- : CALL: FunnelService.achieveGoal api_url: no343.infusionsoft.com api_key:<apikey> at:2015-10-28 16:45:56 -0600 args:["no343", "payingcustomer", 1234]
```

I am running this as a test from the rails console as well if that makes a difference.

Thanks.

**Comment by samcambridge** [comment]
Hey, I'm also getting this error when calling the `funnel_achieve_goal` method, thought my error is slightly different (Wrong size. Was 1070, should be 309) it's fundamentally the same. @sftsang did you get any further with this issue?

**Comment by samcambridge** [comment]
After doing a bit of digging it seems to be an issue with xmlrpc clients in ruby 2, http://stackoverflow.com/questions/15640764/ruby-2-0p0-and-xmlrpcclient

**Comment by nateleavitt** [comment]
Glad you guys found the issue :+1:
