### ISSUE TITLE
Error loading follow-up sequence

### ISSUE THREAD

**Issue by mhassaan** [nateleavitt/infusionsoft#51]
Hi @nateleavitt i am integrating this gem in my rails app and i am facing the same issue with some of the methods. Like when i try to make an api call to add contac to campaign

`contact_id = Infusionsoft.contact_add_with_dup_check({ FirstName:'Bill', LastName:'Joe', Email:'bill@gmail.com' }, 'ContactName') `

`Infusionsoft.contact_add_to_campaign(contact_id,2)`

This throws an error 
`<Infusionsoft::LoadingError: [Loading]Error loading follow-up sequence>
`
Any update on this ?

**Comment by nateleavitt** [comment]
@mhassaan - So you are trying to run followup sequence (campaign) id 2. Does that exist? From the error it looks as if Campaign id 2 doesn't exist.

**Comment by Spoowy** [comment]
@nateleavitt I ran into the same issue. I had a wrong campaign id(follow-up sequence id).

**Comment by mhassaan** [comment]
@nateleavitt yeah it was a mistake, I was using wrong id. Thanks for update guys.
