### ISSUE TITLE
List of all Contacts 

### ISSUE THREAD

**Issue by saazzou** [nateleavitt/infusionsoft#55]
Hello,

Is there a way to get all Contacts without specific cretaria ?

Many thanks

**Comment by jaredjackson** [comment]
This is a question for a place like stackoverflow ...

http://stackoverflow.com/questions/41963025/is-there-a-way-to-get-all-contacts-without-specific-criteria

**Comment by nateleavitt** [comment]
Thanks @jaredjackson
