### ISSUE TITLE
Bug? ... InvoiceService.addRecurringOrder

### ISSUE THREAD

**Issue by jaredjackson** [nateleavitt/infusionsoft#58]
The method invoice_add_recurring_order doesn't seem to work in the master branch due to the fact that not all the parameters that are listed as required under the Infusionsoft API docs are present in this method.

The missing parameters are: "qty", "price", "allowTax".

My assumption may be off, but either this method doesn't work correctly (because the required params are missing) or those three items aren't actually required parameters. Not sure if anyone else uses the method as is and without issue.

Regardless, I have been using a modified method to support all of the required parameters and the transactions are properly submitted via the api. When I revert back to using the master branch (nateleavitt/infusionsoft), the transactions fail.

This may be due to the fact that my application allows for variable pricing in the recurring order.

**Question:** would this be a case where the method could be modified to fully support the API docs, or would it be better to add a second method like, invoice_add_custom_recurring_order ... to avoid breaking some application that is currently using it successfully as is?

**Comment by TravisSperry** [comment]
This had worked for us before in the past with no error so I'm not sure what change caused the error. In our case, the sub gets created even though the unexpected error is thrown.

**Comment by jaredjackson** [comment]
Yes, I have a branch with the only change being the fix the the invoice_add_recurring_order method.

But I'd like to hear from Nate when he gets a chance to know if he has any insight on how the change might impact current users. If it would be too much of a change, I'd create a different branch adding a custom method for full API support.

**Comment by jaredjackson** [comment]
Here is the branch.

https://github.com/jaredjackson/infusionsoft/tree/fix/invoice-add-recurring-order

**Comment by TravisSperry** [comment]
Cool thanks. I can wait. I have a workaround for now. Like I said, the subscription is created even though the error is thrown, so, for now, I'm rescuing and redirecting :/ Making everything appear normal.

**Comment by nateleavitt** [comment]
Hmm... not sure. I'll check out the branch.

**Comment by nateleavitt** [comment]
Interesting.. the API must have been changed. I know that this method had been used before without error. Let me do some additional testing. If the error is thrown regardless I think the only way to proceed is to update the method. Deprecation warnings from the Infusionsoft API would be nice :)

**Comment by jaredjackson** [comment]
It's weird because I've had the same experience as Travis ... Infusion API throws an error but the subscription is still created.

**Comment by TravisSperry** [comment]
@jaredjackson Are you running on Rails 5?

**Comment by jaredjackson** [comment]
Yes ...  5.0.2 ... with Ruby 2.3.1

**Comment by TravisSperry** [comment]
Rails 5 could be the source of the issue. I'm running the same. Why? I'm not sure. I know I had to make some updates to how params were handled but that's not an issue with this call.

**Comment by jaredjackson** [comment]
I'll test some different rails apps and ruby versions when I get a chance later today.

**Comment by jaredjackson** [comment]
For what it's worth, Rails 4.2.8 allows me to successfully add a recurring order via the Infusionsoft gem as is without error. So that is a difference between Rails 4.x and 5.x ... not sure why the difference. It may be deeper in the stack of required gems ...

However, since the Infusionsoft API is stating the other params (qty, price, taxable) are required ... and on a personal level since I use a variable pricing scheme ... I'd suggest the gem be updated to reflect the current API docs.

Still, to prevent breakage on current 4.x apps, I might suggest that a second method that fully supports the API be added with a deprecation warning on the current method. Sooner or later the method will need to be updated as Rails progresses. Any thoughts @nateleavitt, @TravisSperry ?

**Comment by jaredjackson** [comment]
UPDATE .... I just tested another fresh install with Rails 5.0.3 and successfully created a new recurring order with the current Infusionsoft gem (unmodified). So maybe more testing with other versions of Rails to nail it down.

**Comment by jaredjackson** [comment]
I think at this point, my theory is that Infusionsoft infers the qty, price, and taxable params from the subscription plan. So even though the API docs say those are required in the API call, the IS side is supplying those values if they aren't submitted through the API call. Still digging.

**Comment by nateleavitt** [comment]
@jaredjackson I like your idea of updating the current call with a deprecation warning, and adding a second method to reflect the current Infusionsoft API docs. I really want to do a rewrite of this gem.. but it's on my long to-do list :P

**Comment by TravisSperry** [comment]
@jaredjackson I will try bumping to 5.0.3. Thanks!

**Comment by jaredjackson** [comment]
In this branch ... https://github.com/jaredjackson/infusionsoft/tree/fix/invoice-add-recurring-order

I kept the original method and added a deprecation warning. Then the new replacement method. Also added tests/VCR cassettes.

**Comment by nateleavitt** [comment]
Awesome! Created a pull request from your branch:
https://github.com/nateleavitt/infusionsoft/pull/60

**Comment by nateleavitt** [comment]
This has now been merged and deployed in the newest version of the gem.
