### ISSUE TITLE
Searching Contacts by Custom Fields

### ISSUE THREAD

**Issue by sneakernets** [nateleavitt/infusionsoft#61]
Is it possible to search for a contact or any other table by custom fields? My company has "Retail ID" that is in every contact custom fields, and is unique for each one. I can't figure out how to search for contacts by that specific field. I was hoping there would be a way to link those tables. Am I missing something?

**Comment by sneakernets** [comment]
Aaahh never mind I figured it out. Great gem by the way!

**Comment by zstrad44** [comment]
@sneakernets  What was the solution, if you don't mind me asking?
