### ISSUE TITLE
Get contact id using the email

### ISSUE THREAD

**Issue by edgsv** [nateleavitt/infusionsoft#62]
Is there a way to pull a contact's id from infusionsoft if I have the contact email in my database?

**Comment by jaredjackson** [comment]
This is not a gem issue. It's a question about usage. Please post questions like this to an appropriate forum like stackoverflow ...

Here is the answer you're seeking.

https://stackoverflow.com/questions/46669351/how-to-get-contact-id-using-email-address-with-infusionsoft-gem

**Comment by nateleavitt** [comment]
Thanks @jaredjackson
