### ISSUE TITLE
No such handler: InvoiceService.getinvoice_id

### ISSUE THREAD

**Issue by maneeshacd** [nateleavitt/infusionsoft#68]
There is an issue with `InvoiceService.getinvoice_id` API call in `infusionsoft/lib/infusionsoft/client/invoice.rb` line number 300. Its actually `InvoiceService.getInvoiceId` Please refer this PR - https://github.com/nateleavitt/infusionsoft/pull/69

**Comment by nateleavitt** [comment]
Ok thank you. Merged!
