### ISSUE TITLE
Can't retrieve a contact.

### ISSUE THREAD

**Issue by ESouza** [nateleavitt/infusionsoft#76]
Hello @nateleavitt I am having an issue retrieving a contact.

**If I run:**
Infusionsoft.contact_load('327950')

**I get:**
InfusionAPIError: No method matching arguments: java.lang.String, java.lang.Integer, [Ljava.lang.Object;, java.util.HashMap
from /Users/eduardo.souza/.rvm/gems/ruby-2.6.1@btv/gems/infusionsoft-1.3.6/lib/infusionsoft/exception_handler.rb:28:in `initialize'
Caused by XMLRPC::FaultException: No method matching arguments: java.lang.String, java.lang.Integer, [Ljava.lang.Object;, java.util.HashMap
from /Users/eduardo.souza/.rvm/gems/ruby-2.6.1@btv/gems/xmlrpc-0.3.2/lib/xmlrpc/client.rb:272:in `call'

**If I run:**
Infusionsoft.contact_load('327950', ['FirstName', 'LastName'])

**I get:**
_ArgumentError: wrong number of arguments (given 3, expected 2)
from /Users/eduardo.souza/.rvm/gems/ruby-2.6.1@btv/gems/infusionsoft-1.3.6/lib/infusionsoft/client/contact.rb:69:in `contact_load'_

I have tried as an array, as strings and still nothing works. 

What am I doing wrong here? 

PS.: I was able to successfully add a contact.

**Comment by nateleavitt** [comment]
Hi @ESouza ,

I apologize.. I just realized earlier today that my gem update (1.3.6) is only compatible with Ruby 3. Until I update it go ahead and install 1.3.5 and see if that fixes your problem.

**Comment by ESouza** [comment]
@nateleavitt thank you yes that did solve the issue. Much appreciated it. Thank you

**Comment by ESouza** [comment]
@nateleavitt quick question, if I need to pull all Tags on Keap and possibly add and remove some tags using the gem, how should I go about it? Thank you

**Comment by nateleavitt** [comment]
Hi @ESouza,

There are a couple ways to do that. Since version 1.3.5 I have added the ability to access the rest api with Keap. So you can do it either with the xmlrpc or rest api. I am currently in the process of renaming the gem (keap) and will be adding additional documentation.

For xmlrpc you would do something like this:

```ruby
infusion_tag = {"GroupName" => "Tag Name", "GroupCategoryId" => category_id}
tag_id = Infusionsoft.data_add(:ContactGroup, infusion_tag)
```

for rest you would do this:

```ruby
 payload = {
      category: {
        id: tag_category_id
      },
      description: 'Tag Description',
      name: 'Tag Name'
    }

    # create tag
    tag = Infusionsoft.post('/tags', @token, payload: payload)
```

**Comment by nateleavitt** [comment]
I just read your comment and realized I may have misunderstood.  To pull all tags you would do something like the following:

```ruby
# xmlrpc
# access the `ContactGroup` table (https://developer.infusionsoft.com/docs/table-schema/)
tags = Infusionsoft.data_query(:ContactGroup, 1000, 0, {}, [:Id, :GroupName])
```
or

```ruby
# rest api
tags = Infusionsoft.get("/tags", @token, query: { offset: 0, limit: 1000 })
```

**Comment by ESouza** [comment]
Amazing. Thank you so much for your help.
