### ISSUE TITLE
Adding Contact To Campaign Failing

### ISSUE THREAD

**Issue by efatsi** [nateleavitt/infusionsoft#8]
Hi, I've been working with this gem for the past few days and it's been really great so far. I'm running into an odd problem attempting to add a contact to a campaign through the gem.

```
> Infusionsoft.contact_add_to_campaign(5555, 5)
 => nil 
```

I'd looked at the documentation and was expecting true or false depending on if the campaign adding was a success or not, but no matter what I do with this function I get nil.

Any thoughts as to what this could be?

**Comment by sneakernets** [comment]
Has this been corrected? I'm using this gem specifically to add contacts to campaigns.
