### ISSUE TITLE
Updading Groups(tags)

### ISSUE THREAD

**Issue by ESouza** [nateleavitt/infusionsoft#80]
Hello I have an issue where I am trying to update or create a customer with their associated Groups. But I can't seem to get it working using Infusionsoft.contact_add({:FirstName => first_name, :LastName => last_name, :Email => email, :Groups => tags.join(',')}) or using the contact_update or data_add or data_update. It seems I can only add or delete a single tag at the time. What am I doing wrong? 

When I try to simply do a Infusionsoft.data_update('Contact', 8802, {"Groups" => "123, 321"}) I get an error No Fields sent for Update.

with the contact_add I can get the customer to be created but the tags/groups will not be added. Suggestions?

Thank you

**Comment by nateleavitt** [comment]
Hi.. I don't think you can add to groups at the same time through the xmlrpc library. Try the `add_contact_to_group`. See: https://rubydoc.info/gems/infusionsoft/Infusionsoft/Client/Contact#contact_add_to_group-instance_method

**Comment by nateleavitt** [comment]
Let me know if you have any other questions.
